.Dd $Mdocdate$
.Dt RN 1
.Os
.Sh NAME
.Nm rn
.Nd quickly rename a file
.
.Sh SYNOPSIS
.Nm rn
.Ar pattern
.Ar substitutions ...
.
.Sh DESCRIPTION
.Nm rn
renames a file by removing the parts of
the file name
.Ar pattern
that are enclosed in square brackets
.Li ( [ ] )
and replacing them with the specified
.Ar substitutions .

For example, the following command renames
.Li rn.1
to
.Li rn.7 :
.
.Bd -literal -offset 6n
$ rn rn.[1] 7
.Ed

To use a literal forward slash in
.Ar pattern ,
you can escape it with a backslash.
.
.Sh ARGUMENTS
.Bl -tag
.It Ar pattern
the name of the file to be renamed, but in which the parts to be
substituted are enclosed in square brackets
.Li ( [] )
.It Ar substitutions ...
the replacements, in order, for each
.Li [replacee]
in
.Ar pattern
.El
